enviornment:
	matrix:
	#node.js
	-nodejs_version:"6"

#Install scripts. (runs after repo cloning)
install:
	#Get the latest stable node.js or io.js
	- ps: Install-Product node $env:node_version
	#install modules
	- npm install

#Post-install test scripts.
test_script:
	# Output useful info for debugging
	- node --version
	- npm --version
	# run test
	- npm test

#dont actually build.
build: off
